name: Test
on:
  workflow_dispatch

jobs:
  phase-1:
    strategy:
      matrix:
        region: ["eu-central-1", "eu-west-2"]
    uses: ./.github/workflows/test-helper.yml
    with:
      region: ${{ matrix.region }}
  phase-2:
    strategy:
      matrix:
        region: ["us-east-1", "us-west-2"]
    uses: ./.github/workflows/test-helper.yml
    with:
      region: ${{ matrix.region }}
    needs: [phase-1]
