name: Test
on:
  workflow_dispatch
jobs:
  phase-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ['eu-central-1', 'eu-west-2']
    uses: ./.github/workflows/test-helper.yml
    with:
      region: ${{ matrix.region }}
