name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  validate-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: tag-match
        with:
          text: ${{ github.event.release.tag_name }}
          regex: '^\d+\.\d+\.\d+$'
      - run: echo "Please create tag for release with format like 4.0.1" && exit 1
        if: ${{ steps.regex-match.outputs.match == '' }}

  # Build package and publish a prerelease
  prerelease:
    needs: validate-tag
    runs-on: ubuntu-latest
    steps:
      - run: echo "Its working"
